# Generated by Django 4.1.13 on 2024-02-10 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentfurlaxapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('ORDERED', 'ordered'), ('CANCELLED', 'cancelled'), ('DELIVERED', 'delivered')], max_length=50),
        ),
    ]
